### ISSUE TITLE
SerialPortReader NPE on Windows

### ISSUE THREAD

**Issue by lburaggi** [SignalK/artemis-server#5]
When runnig the server on Windows the following NPE is thrown:
`java.lang.NullPointerException: null
	at nz.co.fortytwo.signalk.artemis.serial.SerialPortReader.isRunning(SerialPortReader.java:277) ~[classes/:?]
	at nz.co.fortytwo.signalk.artemis.serial.SerialPortManager.run(SerialPortManager.java:66) [classes/:?]
`
It is caused by the following:
`		if (!SystemUtils.IS_OS_WINDOWS) {
			this.portFile = new File(portName);
		}
`
in line 85.

**Comment by rob42** [comment]
Fixed
